# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cluster-secrets
    namespace: flux-system
stringData:
    SECRET_DOMAIN: ENC[AES256_GCM,data:p0x+sDwa6qF9+2U=,iv:qh0075lkx6N4JLw0kwFqWUHAmljSX0F5tfVFQhOSsBs=,tag:wMdxhzE+sM4br5cGDJ63cw==,type:str]
    SECRET_CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:8LA/zM97Olpup2n6OvfADwBXe2LvnTVMSw==,iv:JNQuagbXX1NmuT9lmV0YaftssAWOuKsconTrT+xz9js=,tag:eLQWuYTKf7GUp22v8QWE+Q==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3cjVXcDUwRndTWE9FYndo
            U0dIQUU2TVBpREZUellXaDhLUnBxRDYzNmtzCkZTblZHSWpxZ1FOM2poekhCYUFH
            SFJLY2hINlkwTjh5K1B4WC9pR2ZQaEEKLS0tIGtkUmx3VVVFNjU3aktMeXpWblJn
            ZnphbXM3RDlyQzFrNlJBT2dmS0ovUFEKwJj9p75dT/KErReIvT8nALaDQrnHOb9T
            +FMhVT7F/Tc/dhWWHGomEuau1IKT4vXVcCrx8zDg+GOhyfHORCvNyg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T09:54:36Z"
    mac: ENC[AES256_GCM,data:XTHhf3rK6BR7Z/v00M/2AS/CXi9ivuyVt5Z2Ls0upe7OTuZzBAB6UKaR91J3EH/wI4v/ANCU/N1TaRqgsZGtn2s0Phnw0xasMkE22Rwx5ZOuTQ7HBfiia6+JriRh70aqLCHlf+Lkkczaf4b6ofzs66NMTRKBHPR//VWpZMbR8/k=,iv:ARmsjWTagKnzxwEZy9kavN5pVWv8aSSz7KgtLyZlXVg=,tag:y7/JMZQrXQmaw27JNO59iQ==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
