# yamllint disable
apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-key
    namespace: cert-manager
stringData:
    api-key: ENC[AES256_GCM,data:q+6sAyK8JerNopk+sfgQr9PlewePOVszLmvnVppuiPesy38Bwg==,iv:reMGENuJGq7XXIa/J6hAnJT5lgaoCSp9rz+54lO2Vb0=,tag:70K5poNZmOhB7GfMC6c0oQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1w5n9srawz0e4rrxtmm4fq9he9r7t5jy3w5jr7r40tz9ksy2txcssvlaw5t
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2V200ZmwyWWxVMW01SHJ0
            S0htSUI2dUIzSEk5dmcweGhPSUpIY2c2ZGtRCkxWd1R0dkg5Vzk3Rm1LL044M1Nj
            L2E4cVhKS3pBSE5YY2dhK1lVRUE3T1UKLS0tIDI5aG81UURJZWthZWVqOUFFa1hC
            bWE5N1p4dFQwbDZWclRyLy9LVGlmZmcK7VqQga7RVqC34sHtoJZJizeaFGMttNHL
            rZbaWFNK42JhX0RpF+RaRqBMzzUfKg7KHSk5/hlBg9Mb9i5J0eJg2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2022-02-28T09:54:36Z"
    mac: ENC[AES256_GCM,data:plRq1ZjMJlEVWm1xE8J0/VS1ZGmfRo5GM3RYKkOAagbvBhQ7grembnCRuGD0GKZbdVwluH3G3AMmowuLkNAy6yXuZz9UXVpWNzN0g4X1f02o7287ijl8psjqUJmht1e69C7rIxSmITwknBQmk/O5KDYrOp0o4R+4FGy6Zuvp33U=,iv:1PF8gqYvBrbzz76TEOFuFoGYumV3WlXhycUTqi7PMCo=,tag:K3VQUAmKEOhzwj3vBN73/g==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.1
